# Generated by Django 2.2.2 on 2019-06-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('body', models.TextField()),
                ('request_country', models.CharField(max_length=50)),
                ('end_date', models.DateField()),
                ('size', models.CharField(max_length=30)),
                ('request_text', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Sell_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=30)),
                ('account_number', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField()),
                ('method', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
