# Generated by Django 2.2.2 on 2019-06-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_buy_list_sell_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_list',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='sell_list',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
