# Generated by Django 2.2.2 on 2019-06-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190629_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_list',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='sell_list',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
