# Generated by Django 2.2.2 on 2019-06-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190629_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_list',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sell_list',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
