# Generated by Django 2.2.2 on 2019-06-30 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190629_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy_list',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sell_list',
            name='image',
        ),
    ]
